"""add allow_text to poll

Revision ID: 615b95beaf24
Revises: 4a373782a05a
Create Date: 2025-12-12 17:45:16.332447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '615b95beaf24'
down_revision = '4a373782a05a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poll', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allow_text', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poll', schema=None) as batch_op:
        batch_op.drop_column('allow_text')

    # ### end Alembic commands ###
